import json
import os
import datetime
import logging

def run_scraper():
    """Generate a dummy draft contract for testing."""
    draft_dir = os.path.join(os.path.dirname(__file__), '..', 'drafts')
    os.makedirs(draft_dir, exist_ok=True)

    today = datetime.datetime.now().strftime("%Y-%m-%d")
    resolution = (datetime.datetime.now() + datetime.timedelta(days=30)).strftime("%Y-%m-%d")

    sample_draft = {
        "title": "Will Memphis City Council pass the 2025 budget by September?",
        "description": "A test contract generated by run_scraper() in app/scraper.py.",
        "resolution_date": resolution,
        "source": "Daily Memphian",
        "url": "https://dailymemphian.com/example-budget-article",
        "domain": "local"
    }

    draft_path = os.path.join(draft_dir, 'refined_drafts.json')

    with open(draft_path, 'w') as f:
        json.dump([sample_draft], f, indent=2)

    logging.info(f"✅ Draft written to {draft_path}")

