"""Add news_headline table

Revision ID: 36eddb8e4bcf
Revises: 4dc044be0665
Create Date: 2025-06-25 10:13:05.679225

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36eddb8e4bcf'
down_revision = '4dc044be0665'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('news_headline',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('url', sa.String(length=200), nullable=True),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('date_added', sa.DateTime(), nullable=True),
    sa.Column('date_published', sa.DateTime(), nullable=True),
    sa.Column('domain_tag', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['news_source.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('news_headline')
    # ### end Alembic commands ###
