"""Add name column to Contract

Revision ID: 53eb04838887
Revises: 4fcbc4274c0d
Create Date: 2025-06-28 19:28:57.339923

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53eb04838887'
down_revision = '4fcbc4274c0d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contract', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=128), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contract', schema=None) as batch_op:
        batch_op.drop_column('name')

    # ### end Alembic commands ###
