"""Add created_at to user_badges table and improve badge relationships

Revision ID: 7fd80d488620
Revises: 04266d0291ee
Create Date: 2025-06-26 18:57:31.915199

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7fd80d488620'
down_revision = '04266d0291ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_badges', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_badges', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
