"""Make market_id nullable in MarketEvent

Revision ID: 88825c9760ed
Revises: a9501276c33f
Create Date: 2025-07-03 22:07:21.779440

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88825c9760ed'
down_revision = 'a9501276c33f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('market_event', schema=None) as batch_op:
        batch_op.alter_column('market_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('prediction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('xp_awarded', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prediction', schema=None) as batch_op:
        batch_op.drop_column('xp_awarded')

    with op.batch_alter_table('market_event', schema=None) as batch_op:
        batch_op.alter_column('market_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
