"""add user_ledger table

Revision ID: 949253c51e37
Revises: 50bbaa2eda7e
Create Date: 2025-06-28 23:55:45.371350

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '949253c51e37'
down_revision = '50bbaa2eda7e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('market', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=20),
               existing_nullable=True)

    with op.batch_alter_table('market_events', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=256),
               nullable=False)

    with op.batch_alter_table('predictions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('points_awarded', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('xp_awarded', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('predictions', schema=None) as batch_op:
        batch_op.drop_column('xp_awarded')
        batch_op.drop_column('points_awarded')

    with op.batch_alter_table('market_events', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=256),
               nullable=True)

    with op.batch_alter_table('market', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=10),
               existing_nullable=True)

    # ### end Alembic commands ###
