"""Add liquidity_buffer_deposit to User model

Revision ID: b1fe79eda1e0
Revises: 7fd80d488620
Create Date: 2025-06-27 09:57:37.426941

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1fe79eda1e0'
down_revision = '7fd80d488620'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('liquidity_buffer_deposit', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('liquidity_buffer_deposit')

    # ### end Alembic commands ###
