"""Initial recovery migration

Revision ID: cfcb22ecb79e
Revises: 
Create Date: 2025-07-01 00:16:06.571936

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cfcb22ecb79e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('badges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contract_drafts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('city', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('actor', sa.String(length=128), nullable=True),
    sa.Column('scope', sa.Text(), nullable=True),
    sa.Column('timeline', sa.String(length=128), nullable=True),
    sa.Column('refined_title', sa.String(length=256), nullable=True),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('bias_score', sa.Float(), nullable=True),
    sa.Column('stage_log', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('league',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('news_source',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('url', sa.String(length=200), nullable=False),
    sa.Column('selector', sa.String(length=100), nullable=False),
    sa.Column('date_selector', sa.String(length=100), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_badges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('badge_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('league_member',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('league_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('joined_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['league_id'], ['league.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('news_headline',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['news_source.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('published_contracts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('draft_id', sa.Integer(), nullable=True),
    sa.Column('city', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('actor', sa.String(length=128), nullable=True),
    sa.Column('resolution_method', sa.String(length=256), nullable=True),
    sa.Column('source_url', sa.String(length=512), nullable=True),
    sa.Column('resolution_date', sa.DateTime(), nullable=True),
    sa.Column('current_odds_yes', sa.Float(), nullable=True),
    sa.Column('current_odds_no', sa.Float(), nullable=True),
    sa.Column('xp_threshold', sa.Integer(), nullable=True),
    sa.Column('total_volume_points', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['draft_id'], ['contract_drafts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('published_contracts')
    op.drop_table('news_headline')
    op.drop_table('league_member')
    op.drop_table('user_badges')
    op.drop_table('news_source')
    op.drop_table('league')
    op.drop_table('contract_drafts')
    op.drop_table('badges')
    # ### end Alembic commands ###
